### ISSUE TITLE
[FEATURE REQUEST] Erode bottom layers only

### ISSUE THREAD

**Issue by RebelKeithy** [sn4k3/PrusaSL1Viewer#1]
**Is your feature request related to a problem? Please describe.**
When printing on SLA printers the bottom layers must be over exposed to adhere to the build plate. This causes these layers to expand.

**Describe the solution you'd like**
To prevent this expansion from making the bottom layers larger than the normal layers, I would like to be able to erode just the bottom layers.

**Additional context**
Adding a checkbox to the erode menu to have it operate on just the bottom layers to be perfect.

**Comment by sn4k3** [comment]
The feature you request is already being implemented, will be avaliable on next build as many other news ;)

**Comment by RebelKeithy** [comment]
That's awesome. This is a great app for filling in features missing in slicers. In the meantime I've managed to hardcode it to only erode the first 6 layers 😄

**Comment by sn4k3** [comment]
Here the last dev with that feature: https://easyupload.io/3ffnmh

**Comment by RebelKeithy** [comment]
Just used to print some dungeon tiles. It works great. Thanks!

**Comment by sn4k3** [comment]
It's now possible to fade erode, decreasing the iteration over layer height for better overexposure solution
